apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jxukt3d7m-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jxukt3d7m-java-quarkus-gitops